### ISSUE TITLE
Error al procesar pago con tarjeta magento 2.0.15

### ISSUE THREAD

**Issue by kabulin** [conekta/conekta-magento2#13]
Hola, buenas tardes.

Tengo un problema al procesar el pago con tarjeta, hace la tokenización bien pero me envia un error. Al revisar los logs, este es el error que aparece en el archivo de exception.log:

main.CRITICAL: exception 'Exception' with message 'Report ID: webapi-59763d9366078; Message: Notice: Undefined index: cc_bin in /var/www/html/vendor/conekta/magento2-module/Model/Card.php on line 141' in /var/www/html/vendor/magento/framework/Webapi/ErrorProcessor.php:194

Al parecer es en la linea 141, no encuentra el indice cc_bin, donde esta la seccion de PCI assurance.

Tendran alguna sugerencia para corregir este problema?. El pago con oxxo funciona correctamente, es solamente en el pago con tarjeta.

Saludos y muchas gracias, si necesitan más información me dicen.

Víctor

**Comment by eduardoconekta** [comment]
Hola @kabulin Víctor te recomendamos hacer updgrade de tu version a la 2.2.0 que es con la que hemos estado haciendo pruebas, posiblemente hubo cambios en la forma de llamar el bin de esa version a esta. Tambien te recordamos que actualmente no tenemos compatibilidad con algún checkout custom por el momento asi que si tienes alguno instalado te pedimos que hagas las pruebas deshabilitandolo

**Comment by kabulin** [comment]
Hola @eduardoconekta ,

Gracias por la respuesta, vamos a intentar con la version 2.2.0. 

Les sugiero que actualicen esta información, ya que dice que solo esta probado en magento 2.0.7. 

Saludos y muchas gracias,

**Comment by eduardoconekta** [comment]
Claro @kabulin y te invitamos a probar nuestro proximo release estable que saldrá en esta semana  que corrige algunos bugs de la version beta y hace llamadas al api 2 de conekta, incluso si estas al pendiente hoy podamos liberarla
