### ISSUE TITLE
Webhook Error, Front controller reached 100 router match iterations

### ISSUE THREAD

**Issue by adriandiazdeleon** [conekta/conekta-magento2#27]
El webhook no funciona.

Al entrar a la cuenta en Conekta, la sección para configuración de webhooks muestra el estado con error.
https://admin.conekta.com/settings/webhooks

Al visitar el URL del webhook muestra el siguiente error:

```
1 exception(s):
Exception #0 (LogicException): Front controller reached 100 router match iterations

Exception #0 (LogicException): Front controller reached 100 router match iterations
#0 /var/www/html/magento-site/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#1 /var/www/html/magento-site/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#2 /var/www/html/magento-site/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/magento-site/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/magento-site/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#5 /var/www/html/magento-site/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#6 /var/www/html/magento-site/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /var/www/html/magento-site/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#8 /var/www/html/magento-site/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /var/www/html/magento-site/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#10 /var/www/html/magento-site/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#11 {main}
```

**Comment by neutronixx** [comment]
Alguna noticia sobre la resolución de este problema?

**Comment by adriandiazdeleon** [comment]
Parece que arregle el problema...

Hice varios ajustes al codigo mientras hacía debugging pero me parece el fix fue en la definición de la función __construct en conekta\conekta_payments\Controller\Webhook\Index.php linea 10

```
<?php

namespace Conekta\Payments\Controller\Webhook;

use Magento\Framework\App\Action\Action;
use Magento\Sales\Model\Order;

class Index extends Action {

    public function __construct(\Magento\Framework\App\Action\Context $context) {
      parent::__construct($context);
    }

```
eliminando el uso de la variable $logger, y sustituyendo el metodo para loggear por esta:
```
\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->critical('Error processing payment', ['exception' => $e]);
```

**Comment by eduardoconekta** [comment]
@adriandiazdeleon gracias por el fix Adrian

**Comment by eduardoconekta** [comment]
https://github.com/conekta/conekta-magento2/pull/28

**Comment by jasongarciagarciak** [comment]
Buena tarde, he aplicado la solución de cambiar el uso de la función logger por " conekta\conekta_payments\Controller\Webhook\Index.php linea"
Pero obtengo el error que esta abajo, la versión de magento que estoy utilizando es   2.2.5, de antemano gracias por su apoyo.

{"0":"Front controller reached 100 router match iterations","1":"#0 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#1 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#2 \/var\/www\/html\/magento2\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#3 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/var\/www\/html\/magento2\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#5 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/var\/www\/html\/magento2\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#8 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/var\/www\/html\/magento2\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#10 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#11 \/var\/www\/html\/magento2\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#12 {main}","url":"\/conekta\/webroot@kokozone-app-5cddf7b9-9777j

**Comment by adriandiazdeleon** [comment]
Seria mejor si incluyeras cómo quedo tu código (las primeras 12 lineas de conekta\conekta_payments\Controller\Webhook\Index.php)

En resumen debes eliminar el uso de la variable $logger dentro de los parámetros de la función __construct().

Ya si sistituyes o no el metodo de loggear es irrelevante.

**Comment by adriandiazdeleon** [comment]
Seria mejor si incluyeras cómo quedo tu código (las primeras 12 lineas de conekta\conekta_payments\Controller\Webhook\Index.php)

En resumen debes eliminar el uso de la variable $logger dentro de los parámetros de la función __construct().

Ya si sistituyes o no el metodo de loggear es irrelevante.

**Comment by jasongarciagarciak** [comment]
Este el código que tengo en el archivo:
/var/www/html/magento2/vendor/conekta/conekta_payments/Controller/Webhook/Index.php

Igual comentado la linea en el try sigue mandando el mismo error.
----
<?php
namespace Conekta\Payments\Controller\Webhook;
use Magento\Framework\App\Action\Action;
use Magento\Sales\Model\Order;
class Index extends Action {
    public function __construct(\Magento\Framework\App\Action\Context $context) {
        parent::__construct($context);
    }
    public function execute() {
        $body = @file_get_contents('php://input');
        $event = json_decode($body);

        $charge = $event->data->object;
        $order = $this->_objectManager->create('Magento\Sales\Model\Order');

        if ($charge->status === "paid"){
            try{
                $order->loadByIncrementId($charge->reference_id);
                $order->setSate(Order::STATE_PROCESSING);
                $order->setStatus(Order::STATE_PROCESSING);
                $order->addStatusHistoryComment("Payment received successfully")
->setIsCustomerNotified(true);
                $order->save();
                header('HTTP/1.1 200 OK');
                return;
            } catch (\Exception $e) {
                    Magento\Framework\App\ObjectManager::getInstance()
->get(\Psr\Log\LoggerInterface::class)->critical('Error processing payment', ['exception' => $e]);
            }
        }
    }
}

**Comment by adriandiazdeleon** [comment]
Que raro, lo tengo practicamente igual, la unica diferencia es que (no recuerdo si lo agregue yo a mi fix o ya estaba en codigo) evaluo si  isset($event->data) antes de asignar datos a $charge.

Fuera de eso puede que necesites clear/flush cache o correr 
$ php bin/magento setup:upgrade

Este es mi codigo tal cual:

```
<?php

namespace Conekta\Payments\Controller\Webhook;

use Magento\Framework\App\Action\Action;
use Magento\Sales\Model\Order;

class Index extends Action {

    public function __construct(\Magento\Framework\App\Action\Context $context) {
      parent::__construct($context);
    }
  
    public function execute() {
        \Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->info('Controller Action Conekta\Payments\Controller\Webhook\Index executed...');
        $body = @file_get_contents('php://input');
        $event = json_decode($body);
      
        \Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->info('Webhook recieved object', array('$body'=>$body));
        
        if(isset($event->data)) {
            $charge = $event->data->object;
            $order = $this->_objectManager->create('Magento\Sales\Model\Order');

            if ($charge->status === "paid"){
                try{ 
                    $order->loadByIncrementId($charge->reference_id);
                    $order->setSate(Order::STATE_PROCESSING);
                    $order->setStatus(Order::STATE_PROCESSING);

                    $order->addStatusHistoryComment("Payment received successfully")->setIsCustomerNotified(true);

                    $order->save();

                    header('HTTP/1.1 200 OK');
                    return;
                } catch (\Exception $e) {
                    \Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->critical('Error processing payment', ['exception' => $e]);
                }
            } 
        }
    }
}

```

**Comment by jasongarciagarciak** [comment]
Muchas gracias por tu tiempo, ya puse el mismo código que me hiciste favor de proporcionar limpie cache he hice el upgrade pero sigo recibiendo.

```
"0":"Front controller reached 100 router match iterations","1":"#0 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#1 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#2 \/var\/www\/html\/magento2\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#3 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/var\/www\/html\/magento2\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#5 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/var\/www\/html\/magento2\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#8 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/var\/www\/html\/magento2\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#10 \/var\/www\/html\/magento2\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#11 \/var\/www\/html\/magento2\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#12 {main}","url":"\/conekta\/webhook\/listener","script_name":"\/index.php"}
```
