### ISSUE TITLE
dependency is broken: conekta-php-namespaces 

### ISSUE THREAD

**Issue by adler99** [conekta/conekta-magento2#4]
Hi,
following your installation instruction I get the following:
 Failed to download sairoko12/conekta-php-namespaces from dist: The "https://api.github.com/repos/sairoko12/conekta-php/zipball/97b3e4e51ea3bb1085a0ca2308b2524455ca7a1c" file could not be downloaded (HTTP/1.1 404 Not Found)
Thanks for looking into it!
Martin

**Comment by GmemoS** [comment]
Hi adler99,
Try using **composer require conekta/magento2-module dev-composer** instead **composer require conekta/magento2-module dev-master**, in the second step to install.

**Comment by adler99** [comment]
Thanks
