### ISSUE TITLE
Webhook failed

### ISSUE THREAD

**Issue by JonatanGarces** [conekta/conekta-magento2#5]
Hola!
En el portal de conekta me aparece como error.
La url del webhook es la siguiente  **sitio/conekta/webhook/listener**
Saludos

**Comment by azuniaga** [comment]
Hola ! tengo este mismo problema, no se que colocar en ese campo 
"Default webhook is: your_magento_host/conekta/webhook/listener"

**Comment by eduardoconekta** [comment]
@azuniaga  si mi tienda fuera https://compraproductos.com
mi webhook seria https://compraproductos.com/webhook/listener 

te dejo la documentación de webhooks :)
https://developers.conekta.com/resources/webhooks
